// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxowsihwcbbxtfqrpyvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b3dzaWh3Y2JieHRmcXJweXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDQ2ODgsImV4cCI6MjA2OTM4MDY4OH0.fvl2ChqFTaJotIp5ofIGBfHY01UYqF7Z1lt9h2vl88U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});